// frontend/src/components/groups/GroupFormDialog.tsx
// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes

import { useCallback, useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";
import type { JSX } from "react";
import { Loader2 } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { type Group, listOrganizations, type Organization } from "@/lib/api";
import {
  captureAuthOwner,
  captureAuthPrincipalGeneration,
  isCurrentAuthOwner,
  onAuthOwnerReplacement,
  subscribeAuthPrincipal,
  type AuthOwner,
} from "@/lib/api/auth-lifecycle";

// ============================================================================
// Types
// ============================================================================

export interface GroupFormData {
  name: string;
  description: string;
  org_id?: number | null;
}

interface GroupFormDialogProps {
  mode: "create" | "edit";
  group?: Group | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSubmit: (data: GroupFormData) => Promise<void>;
  isLoading?: boolean;
}

// ============================================================================
// Validation
// ============================================================================

function validateGroupForm(data: GroupFormData): Record<string, string> {
  const errors: Record<string, string> = {};
  
  if (!data.name || data.name.trim().length === 0) {
    errors.name = "Group name cannot be empty";
  } else if (data.name.trim().length < 2) {
    errors.name = "Group name must be at least 2 characters";
  } else if (data.name.length > 100) {
    errors.name = "Group name must be less than 100 characters";
  }
  
  if (data.description && data.description.length > 500) {
    errors.description = "Description must be less than 500 characters";
  }
  
  return errors;
}

// ============================================================================
// Main Component
// ============================================================================


type OrganizationReadState =
  | { status: "unknown" }
  | { status: "loading" }
  | { status: "success" }
  | { status: "error"; message: string };

interface GroupDialogContext {
  openingToken: number;
  owner: AuthOwner;
  principalGeneration: number;
  open: boolean;
  mode: "create" | "edit";
  groupId: number | null;
}

const emptyGroupFormData: GroupFormData = {
  name: "",
  description: "",
  org_id: null,
};

const subscribeAuthOwner = (listener: () => void): (() => void) =>
  onAuthOwnerReplacement(() => listener());


function GroupFormDialogPanel({
  mode,
  group,
  open,
  onOpenChange,
  onSubmit,
  isLoading = false,
}: GroupFormDialogProps): JSX.Element {
  const isEdit = mode === "edit";
  const title = isEdit ? "Edit Group" : "Create Group";
  const description = isEdit
    ? `Update details for ${group?.name || "this group"}`
    : "Create a new group to organize users and manage vault access.";
  const submitLabel = isEdit ? "Save Changes" : "Create Group";
  const authOwner = useSyncExternalStore(subscribeAuthOwner, captureAuthOwner, captureAuthOwner);
  const principalGeneration = useSyncExternalStore(
    subscribeAuthPrincipal,
    captureAuthPrincipalGeneration,
    captureAuthPrincipalGeneration,
  );
  const mountedRef = useRef(false);
  const principalGenerationRef = useRef(principalGeneration);
  principalGenerationRef.current = principalGeneration;
  const openingIdentityRef = useRef({ signature: "", token: 0 });
  const openingSignature = `${open ? "open" : "closed"}:${mode}:${group?.id ?? "new"}:${authOwner.id}:${principalGeneration}`;
  if (openingIdentityRef.current.signature !== openingSignature) {
    openingIdentityRef.current = { signature: openingSignature, token: openingIdentityRef.current.token + 1 };
  }
  const currentPropsRef = useRef<{ open: boolean; mode: "create" | "edit"; groupId: number | null }>({ open, mode, groupId: group?.id ?? null });
  currentPropsRef.current = { open, mode, groupId: group?.id ?? null };
  const organizationRequestRef = useRef(0);
  const [formData, setFormData] = useState<GroupFormData>(emptyGroupFormData);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [rootError, setRootError] = useState<string | null>(null);
  const [orgs, setOrgs] = useState<Organization[]>([]);
  const [organizationRead, setOrganizationRead] = useState<OrganizationReadState>({ status: "unknown" });
  const organizationReadRef = useRef<OrganizationReadState>(organizationRead);
  const setOrganizationReadState = useCallback((next: OrganizationReadState) => {
    organizationReadRef.current = next;
    setOrganizationRead(next);
  }, []);
  const submitLockRef = useRef<{ openingToken: number; active: boolean } | null>(null);
  const [submitBusy, setSubmitBusy] = useState(false);
  const groupId = group?.id ?? null;
  const groupName = group?.name;
  const groupDescription = group?.description;
  const groupOrgId = group?.org_id;
  const openingToken = openingIdentityRef.current.token;
  const currentContext = useMemo<GroupDialogContext>(
    () => ({
      openingToken,
      owner: authOwner,
      principalGeneration,
      open,
      mode,
      groupId,
    }),
    [authOwner, groupId, mode, open, openingToken, principalGeneration],
  );
  const isSubmitBusy = submitBusy && submitLockRef.current?.active === true &&
    submitLockRef.current.openingToken === currentContext.openingToken;
  const isCurrentContext = useCallback((context: GroupDialogContext): boolean => {
    const currentProps = currentPropsRef.current;
    return context.open && mountedRef.current && context.openingToken === openingIdentityRef.current.token &&
      context.open === currentProps.open && context.mode === currentProps.mode &&
      context.groupId === currentProps.groupId &&
      context.principalGeneration === principalGenerationRef.current &&
      captureAuthPrincipalGeneration() === context.principalGeneration && isCurrentAuthOwner(context.owner);
  }, []);
  useEffect(() => {
    mountedRef.current = true;
    return () => { mountedRef.current = false; organizationRequestRef.current += 1; };
  }, []);
  const loadOrganizations = useCallback((context: GroupDialogContext) => {
    if (!isCurrentContext(context) || context.mode !== "create") return;
    const requestToken = ++organizationRequestRef.current;
    setOrganizationReadState({ status: "loading" });
    setOrgs([]);
    void listOrganizations().then((data) => {
      if (!isCurrentContext(context) || organizationRequestRef.current !== requestToken) return;
      if (!Array.isArray(data)) throw new Error("Organization response was invalid");
      if (!isCurrentContext(context) || organizationRequestRef.current !== requestToken) return;
      setOrgs(data);
      setOrganizationReadState({ status: "success" });
      if (data.length === 1 && isCurrentContext(context)) {
        setFormData((prev) => isCurrentContext(context) && organizationRequestRef.current === requestToken && prev.org_id == null ? { ...prev, org_id: data[0].id } : prev);
      }
    }).catch((error: unknown) => {
      if (!isCurrentContext(context) || organizationRequestRef.current !== requestToken) return;
      setOrgs([]);
      setOrganizationReadState({ status: "error", message: error instanceof Error ? error.message : "Unable to load organizations" });
    });
  }, [isCurrentContext, setOrganizationReadState]);
  const handleRetryOrganizations = useCallback(() => {
    if (isCurrentContext(currentContext)) loadOrganizations(currentContext);
  }, [currentContext, isCurrentContext, loadOrganizations]);

  // Reset form when dialog opens/closes or group changes
  useEffect(() => {
    const context = currentContext;
    organizationRequestRef.current += 1;
    if (!context.open) {
      setOrgs([]);
      setOrganizationReadState({ status: "unknown" });
      return;
    }
    setErrors({});
    setRootError(null);
    if (isEdit && groupId !== null) {
      setFormData({ name: groupName ?? "", description: groupDescription || "", org_id: groupOrgId ?? null });
      setOrgs([]);
      setOrganizationReadState({ status: "success" });
      return;
    }
    setFormData(emptyGroupFormData);
    setOrgs([]);
    setOrganizationReadState({ status: "unknown" });
    loadOrganizations(context);
  }, [currentContext, groupDescription, groupId, groupName, groupOrgId, isEdit, loadOrganizations, setOrganizationReadState]);

  // ============================================================================
  // Event Handlers
  // ============================================================================

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const context = currentContext;
    if (!isCurrentContext(context)) return;
    const value = e.target.value;
    setFormData((prev) => isCurrentContext(context) ? { ...prev, name: value } : prev);
    if (errors.name) setErrors((prev) => isCurrentContext(context) ? { ...prev, name: "" } : prev);
  };

  const handleDescriptionChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const context = currentContext;
    if (!isCurrentContext(context)) return;
    const value = e.target.value;
    setFormData((prev) => isCurrentContext(context) ? { ...prev, description: value } : prev);
    if (errors.description) setErrors((prev) => isCurrentContext(context) ? { ...prev, description: "" } : prev);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const context = currentContext;
    if (!isCurrentContext(context) || isLoading) return;
    setRootError(null);
    const catalog = organizationReadRef.current;
    if (!isEdit && catalog.status !== "success") {
      if (isCurrentContext(context)) {
        setRootError(catalog.status === "error" ? "Unable to load organizations. Retry to continue." : "Organizations are still loading.");
      }
      return;
    }
    const validationErrors = validateGroupForm(formData);
    if (Object.keys(validationErrors).length > 0) {
      if (isCurrentContext(context)) setErrors(validationErrors);
      return;
    }
    const activeLock = submitLockRef.current;
    if (activeLock?.active && activeLock.openingToken === context.openingToken) return;
    const lock = { openingToken: context.openingToken, active: true };
    submitLockRef.current = lock;
    setSubmitBusy(true);
    try {
      await onSubmit(formData);
      if (!isCurrentContext(context) || submitLockRef.current !== lock) return;
    } catch (error) {
      if (isCurrentContext(context) && submitLockRef.current === lock) {
        setRootError(error instanceof Error ? error.message : "An error occurred");
      }
    } finally {
      if (submitLockRef.current === lock) {
        lock.active = false;
        if (isCurrentContext(context)) setSubmitBusy(false);
      }
    }
  };

  const handleCancel = () => {
    if (isCurrentContext(currentContext)) onOpenChange(false);
  };

  const handleDialogOpenChange = (nextOpen: boolean) => {
    if (isCurrentContext(currentContext)) onOpenChange(nextOpen);
  };

  // ============================================================================
  // Render
  // ============================================================================

  return (
    <Dialog open={open} onOpenChange={handleDialogOpenChange}>
      <DialogContent className="sm:max-w-[425px]" aria-labelledby="form-title" aria-describedby="form-desc">
        <DialogHeader>
          <DialogTitle id="form-title">{title}</DialogTitle>
          <DialogDescription id="form-desc">{description}</DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4">
            {/* Root Error */}
            {rootError && (
              <div
                role="alert"
                aria-live="polite"
                className="rounded-sm border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive"
              >
                {rootError}
              </div>
            )}

            {/* Name Field */}
            <div className="grid gap-2">
              <Label htmlFor="group-name">
                Group Name <span className="text-destructive">*</span>
              </Label>
              <Input
                id="group-name"
                type="text"
                autoComplete="off"
                disabled={isLoading || isSubmitBusy}
                aria-invalid={!!errors.name}
                aria-describedby={errors.name ? "group-name-error" : undefined}
                value={formData.name}
                onChange={handleNameChange}
              />
              {errors.name && (
                <p id="group-name-error" className="text-sm text-destructive">
                  {errors.name}
                </p>
              )}
            </div>

            {/* Description Field */}
            <div className="grid gap-2">
              <Label htmlFor="group-description">Description</Label>
              <Textarea
                id="group-description"
                rows={3}
                disabled={isLoading || isSubmitBusy}
                placeholder="Enter group description (optional)"
                aria-invalid={!!errors.description}
                aria-describedby={errors.description ? "group-desc-error" : undefined}
                value={formData.description}
                onChange={handleDescriptionChange}
              />
              {errors.description && (
                <p id="group-desc-error" className="text-sm text-destructive">
                  {errors.description}
                </p>
              )}
            </div>

            {/* Organization Field — create mode only */}
            {!isEdit && organizationRead.status !== "success" && (
              <div role={organizationRead.status === "error" ? "alert" : "status"} aria-live="polite" className="grid gap-2">
                {(organizationRead.status === "loading" || organizationRead.status === "unknown") && <p>Loading organizations…</p>}
                {organizationRead.status === "error" && (
                  <>
                    <p>{organizationRead.message}</p>
                    <Button type="button" variant="outline" onClick={handleRetryOrganizations} disabled={isLoading || isSubmitBusy} aria-label="Retry organizations">Retry organizations</Button>
                  </>
                )}
              </div>
            )}
            {!isEdit && organizationRead.status === "success" && orgs.length > 0 && (
              <div className="grid gap-2">
                <Label htmlFor="group-org">
                  Organization {orgs.length > 1 && <span className="text-destructive">*</span>}
                </Label>
                {orgs.length === 1 ? (
                  <div className="grid gap-1">
                    <p className="text-sm">{orgs[0].name}</p>
                    <Input id="group-org" value={orgs[0].name} aria-label={orgs[0].name} disabled aria-readonly="true" />
                  </div>
                ) : (
                  <Select
                    value={formData.org_id !== null && formData.org_id !== undefined ? String(formData.org_id) : ""}
                    onValueChange={(v) => {
                      if (isCurrentContext(currentContext)) setFormData((prev) => isCurrentContext(currentContext) ? { ...prev, org_id: v ? Number(v) : null } : prev);
                    }}
                    disabled={isLoading || isSubmitBusy}
                  >
                    <SelectTrigger id="group-org" aria-label="Select organization">
                      <SelectValue placeholder="Select organization…" />
                    </SelectTrigger>
                    <SelectContent>
                      {orgs.map((org) => (
                        <SelectItem key={org.id} value={String(org.id)}>{org.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                )}
              </div>
            )}
          </div>

          <DialogFooter className="flex-col gap-2 sm:flex-row">
            <Button
              type="button"
              variant="outline"
              onClick={handleCancel}
              disabled={isLoading || isSubmitBusy}
              className="w-full sm:w-auto"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isLoading || isSubmitBusy || (!isEdit && organizationRead.status !== "success")}
              className="w-full sm:w-auto"
              aria-label={submitLabel}
            >
              {isLoading || isSubmitBusy ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" />
                  {isEdit ? "Saving..." : "Creating..."}
                </>
              ) : (
                submitLabel
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}


export function GroupFormDialog(props: GroupFormDialogProps): JSX.Element {
  const authOwner = useSyncExternalStore(subscribeAuthOwner, captureAuthOwner, captureAuthOwner);
  const principalGeneration = useSyncExternalStore(
    subscribeAuthPrincipal,
    captureAuthPrincipalGeneration,
    captureAuthPrincipalGeneration,
  );
  const scopeKey = `${props.open ? "open" : "closed"}:${props.mode}:${props.group?.id ?? "new"}:${authOwner.id}:${principalGeneration}`;
  return <GroupFormDialogPanel key={scopeKey} {...props} />;
}

export default GroupFormDialog;
