// frontend/src/components/groups/ManageMembersSheet.tsx
// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes

import { useState, useEffect, useCallback, useRef } from "react";
import type { JSX } from "react";
import { useQuery } from "@tanstack/react-query";
import { Loader2, Users, Search } from "lucide-react";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Skeleton } from "@/components/ui/skeleton";
import {
  type Group,
  type GroupMember,
  getEligibleGroupMembers,
  getGroupMembers,
} from "@/lib/api";

// ============================================================================
// Types
// ============================================================================

type User = GroupMember;

interface ManageMembersSheetProps {
  group: Group | null;
  open: boolean;
  editorToken?: number;
  onOpenChange: (open: boolean) => void;
  onSave: (userIds: number[]) => Promise<void>;
}

// ============================================================================
// Main Component
// ============================================================================

export function ManageMembersSheet({
  group,
  open,
  editorToken,
  onOpenChange,
  onSave,
}: ManageMembersSheetProps): JSX.Element {
  const [selectedUserIds, setSelectedUserIds] = useState<number[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  const [activeOpeningKey, setActiveOpeningKey] = useState<string | null>(null);
  const [initializedOpeningKey, setInitializedOpeningKey] = useState<string | null>(null);
  const openingKey = open && group ? `${group.id}:${editorToken ?? 0}` : null;
  const currentOpeningKeyRef = useRef<string | null>(openingKey);
  currentOpeningKeyRef.current = openingKey;

  // Fetch eligible users (org members) and current group members
  const {
    data: allUsers,
    isLoading: isLoadingUsers,
    fetchStatus: eligibleMembersFetchStatus,
    status: eligibleMembersStatus,
    isSuccess: isUsersReadSuccessful,
    isError: isUsersReadError,
    refetch: refetchEligibleMembers,
  } = useQuery<User[]>({
    queryKey: ["groups", group?.id, "eligible-members"],
    queryFn: () => getEligibleGroupMembers(group!.id),
    enabled: open && !!group,
  });

  const {
    data: groupMembers,
    isLoading: isLoadingMembers,
    fetchStatus: groupMembersFetchStatus,
    status: groupMembersStatus,
    isSuccess: isMembersReadSuccessful,
    isError: isMembersReadError,
    refetch: refetchGroupMembers,
  } = useQuery<GroupMember[]>({
    queryKey: ["groups", group?.id, "members"],
    queryFn: () => getGroupMembers(group!.id),
    enabled: open && !!group,
  });

  const hasSuccessfulReads =
    eligibleMembersStatus === "success" &&
    groupMembersStatus === "success" &&
    eligibleMembersFetchStatus === "idle" &&
    groupMembersFetchStatus === "idle" &&
    isUsersReadSuccessful &&
    isMembersReadSuccessful &&
    !isUsersReadError &&
    !isMembersReadError;

  // Reset all editor state whenever a new group/opening becomes active. The
  // opening token also changes when the same group is reopened, so a stale
  // save cannot clear or repopulate the newer editor.
  useEffect(() => {
    if (activeOpeningKey === openingKey) {
      return;
    }
    setActiveOpeningKey(openingKey);
    setInitializedOpeningKey(null);
    setSelectedUserIds([]);
    setIsSaving(false);
  }, [activeOpeningKey, openingKey]);

  // Initialize exactly once from successful reads for this opening. A
  // background refetch must not overwrite local edits, and a successful empty
  // response is still a valid empty snapshot.
  useEffect(() => {
    if (
      !openingKey ||
      activeOpeningKey !== openingKey ||
      initializedOpeningKey === openingKey ||
      !hasSuccessfulReads ||
      !allUsers ||
      !groupMembers
    ) {
      return;
    }
    setSelectedUserIds(groupMembers.map((u) => u.id));
    setInitializedOpeningKey(openingKey);
  }, [
    activeOpeningKey,
    allUsers,
    groupMembers,
    hasSuccessfulReads,
    initializedOpeningKey,
    openingKey,
  ]);

  // Reset search when sheet closes
  useEffect(() => {
    if (!open) {
      setSearchQuery("");
    }
  }, [open]);

  // ============================================================================
  // Event Handlers
  // ============================================================================

  const toggleUser = useCallback((userId: number) => {
    setSelectedUserIds((prev) =>
      prev.includes(userId)
        ? prev.filter((id) => id !== userId)
        : [...prev, userId]
    );
  }, []);

  const isLoading = isLoadingUsers || isLoadingMembers;
  const hasReadError = isUsersReadError || isMembersReadError;
  const hasInitializedOpening =
    openingKey !== null &&
    activeOpeningKey === openingKey &&
    initializedOpeningKey === openingKey;
  const hasInitialReadError = !hasInitializedOpening && hasReadError;
  const hasInitialReadPaused =
    !hasInitializedOpening &&
    (eligibleMembersFetchStatus === "paused" || groupMembersFetchStatus === "paused");
  const hasBackgroundReadError = hasInitializedOpening && hasReadError;
  const isReadRetrying =
    eligibleMembersFetchStatus === "fetching" || groupMembersFetchStatus === "fetching";
  const canSave = hasInitializedOpening && !isSaving;

  const retryReads = useCallback(() => {
    void Promise.all([refetchEligibleMembers(), refetchGroupMembers()]).catch(() => {
      // Query state renders retry failures. This callback does not update
      // editor state, so it cannot overwrite a newer opening.
    });
  }, [refetchEligibleMembers, refetchGroupMembers]);

  const handleOpenChange = useCallback((nextOpen: boolean) => {
    if (!nextOpen && isSaving) {
      return;
    }
    onOpenChange(nextOpen);
  }, [isSaving, onOpenChange]);

  const handleSave = useCallback(async () => {
    const submittedOpeningKey = openingKey;
    if (!canSave || !submittedOpeningKey) {
      return;
    }
    setIsSaving(true);
    try {
      await onSave(selectedUserIds);
    } catch {
      // The owning mutation reports the failure. Do not leak a rejected
      // promise from this React event handler.
    } finally {
      if (currentOpeningKeyRef.current === submittedOpeningKey) {
        setIsSaving(false);
      }
    }
  }, [canSave, onSave, openingKey, selectedUserIds]);

  // ============================================================================
  // Filtered Users
  // ============================================================================

  const filteredUsers = (allUsers ?? []).filter((user) => {
    const searchLower = searchQuery.toLowerCase();
    return (
      user.username.toLowerCase().includes(searchLower) ||
      (user.full_name && user.full_name.toLowerCase().includes(searchLower))
    );
  });

  // ============================================================================
  // Render
  // ============================================================================

  return (
    <Sheet open={open} onOpenChange={handleOpenChange}>
      <SheetContent className="sm:max-w-[400px] flex flex-col" aria-labelledby="members-title" aria-describedby="members-desc">
        <SheetHeader>
          <SheetTitle id="members-title" className="flex items-center gap-2">
            <Users className="h-5 w-5" aria-hidden="true" />
            Manage Members
          </SheetTitle>
          <SheetDescription id="members-desc">
            Manage members for <strong>{group?.name}</strong>. Select users to add or remove from this group.
          </SheetDescription>
        </SheetHeader>

        <div className="flex-1 flex flex-col py-4 min-h-0">
          {hasBackgroundReadError && (
            <div
              className="mb-4 flex items-center justify-between gap-3 rounded-sm border border-warning/50 bg-warning/10 p-3 text-sm"
              role="status"
              aria-live="polite"
            >
              <span>The latest member refresh failed. Showing the last loaded members.</span>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={retryReads}
                disabled={isSaving || isReadRetrying}
              >
                Retry
              </Button>
            </div>
          )}
          {/* Search Input */}
          <div className="relative mb-4">
            <Search
              className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"
              aria-hidden="true"
            />
            <Input
              placeholder="Search users..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
              aria-label="Search users"
              disabled={isLoading}
            />
          </div>

          {/* Users List */}
          <ScrollArea className="flex-1 -mx-6 px-6">
            {hasInitialReadError ? (
              <div className="text-center py-8 text-muted-foreground" role="status" aria-live="polite">
                <p>Unable to load group members. Please try again.</p>
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  className="mt-3"
                  onClick={retryReads}
                  disabled={isSaving || isReadRetrying}
                >
                  Retry
                </Button>
              </div>
            ) : hasInitialReadPaused ? (
              <div className="text-center py-8 text-muted-foreground" role="status" aria-live="polite">
                You are offline. Reconnect to load group members.
              </div>
            ) : !hasInitializedOpening && isLoading ? (
              <div className="space-y-3">
                {Array.from({ length: 5 }).map((_, i) => (
                  <div key={i} className="flex items-center gap-3 p-3 rounded-sm border">
                    <Skeleton className="h-4 w-4" />
                    <div className="flex-1 space-y-2">
                      <Skeleton className="h-4 w-32" />
                      <Skeleton className="h-3 w-24" />
                    </div>
                  </div>
                ))}
              </div>
            ) : filteredUsers.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground" role="status" aria-live="polite">
                {searchQuery
                  ? "No users match your search"
                  : (allUsers?.length ?? 0) === 0
                  ? "No org members available. Add users to the organization first."
                  : "No users available"}
              </div>
            ) : (
              <div className="space-y-2 pr-4">
                {filteredUsers.map((user) => (
                  <div
                    key={user.id}
                    className="flex items-start space-x-3 rounded-sm border p-3 hover:bg-muted/50 transition-colors"
                  >
                    <Checkbox
                      id={`user-${user.id}`}
                      checked={selectedUserIds.includes(user.id)}
                      onCheckedChange={() => toggleUser(user.id)}
                      aria-label={`Select ${user.username}`}
                      disabled={isSaving || !hasInitializedOpening}
                    />
                    <Label
                      htmlFor={`user-${user.id}`}
                      className="flex-1 cursor-pointer space-y-1"
                    >
                      <div className="font-medium">{user.username}</div>
                      {user.full_name && (
                        <div className="text-sm text-muted-foreground">
                          {user.full_name}
                        </div>
                      )}
                    </Label>
                  </div>
                ))}
              </div>
            )}
          </ScrollArea>

          {/* Selected Count */}
          <div className="mt-4 text-sm text-muted-foreground">
            {selectedUserIds.length} member{selectedUserIds.length !== 1 ? "s" : ""} selected
          </div>
        </div>

        <SheetFooter className="flex-col gap-2 sm:flex-row border-t pt-4">
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={isSaving}
            className="w-full sm:w-auto"
          >
            Cancel
          </Button>
          <Button
            onClick={handleSave}
            disabled={!canSave}
            className="w-full sm:w-auto"
            aria-label="Save member changes"
          >
            {isSaving ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" />
                Saving...
              </>
            ) : (
              "Save Changes"
            )}
          </Button>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
}

export default ManageMembersSheet;
