"""
Schema-count drift guard (TEST-BE-017).

Asserts the total number of base tables created by ``init_db`` + ``run_migrations``
matches a pinned expected count, and that a curated set of critical tables exist.
This fails loudly if a table is silently added or removed by a migration or
schema change, catching schema drift before it ships.

FTS5 shadow tables (``*_fts``, ``*_fts_config``, ``*_fts_data``, ``*_fts_docsize``,
``*_fts_idx``) are auto-generated by FTS5 virtual tables and are excluded from
the count — they are an implementation detail of the FTS module, not part of
the application's logical schema, and their count can vary by SQLite version.

Baseline measured at HEAD 7070fde: 44 base tables (excluding FTS shadows),
79 total tables (including 35 FTS shadows).
"""
import os
import sqlite3
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

# Expected count of base tables (excluding FTS5 shadow tables). Update this
# constant ONLY when an intentional schema change adds/removes a base table,
# and document the change in the commit message.
# 44 -> 45: master added `document_reindex_jobs` (reindex jobs table).
# 45 -> 46: PR #410 added `failed_chunks` (per-chunk retry identity, Issue #396).
EXPECTED_BASE_TABLE_COUNT = 46

# Curated set of critical application tables that must always exist. If any of
# these disappears, the drift test fails with a clear message naming the table.
# (Note: "documents" are stored in the files/document_tags/document_actions
# tables + LanceDB vectors, not a single documents table.)
CRITICAL_TABLES = {
    "users",
    "user_sessions",
    "files",
    "vaults",
    "vault_members",
    "memories",
    "settings_kv",
    "security_audit_log",
    "wiki_pages",
    "wiki_claims",
    "tags",
}


class TestSchemaDrift(unittest.TestCase):
    """Guard against silent schema drift."""

    @classmethod
    def setUpClass(cls):
        cls.temp_dir = tempfile.mkdtemp()
        cls.db_path = os.path.join(cls.temp_dir, "schema_drift.db")
        from app.models.database import init_db, run_migrations

        init_db(cls.db_path)
        run_migrations(cls.db_path)

    @classmethod
    def tearDownClass(cls):
        import shutil

        try:
            shutil.rmtree(cls.temp_dir)
        except Exception:
            pass

    def _table_names(self):
        conn = sqlite3.connect(self.db_path)
        try:
            rows = conn.execute(
                "SELECT name FROM sqlite_master "
                "WHERE type='table' AND name NOT LIKE 'sqlite_%' "
                "ORDER BY name"
            ).fetchall()
            return [r[0] for r in rows]
        finally:
            conn.close()

    def test_base_table_count_matches_expected(self):
        """The base (non-FTS-shadow) table count must equal the pinned value."""
        names = self._table_names()
        base_tables = [n for n in names if "_fts" not in n]
        actual = len(base_tables)
        self.assertEqual(
            actual,
            EXPECTED_BASE_TABLE_COUNT,
            "Schema drift detected: expected %d base tables, got %d. "
            "Tables: %s. If this change is intentional, update "
            "EXPECTED_BASE_TABLE_COUNT in this test."
            % (EXPECTED_BASE_TABLE_COUNT, actual, sorted(base_tables)),
        )

    def test_critical_tables_exist(self):
        """A curated set of critical application tables must all be present."""
        names = set(self._table_names())
        missing = CRITICAL_TABLES - names
        self.assertFalse(
            missing,
            "Critical tables missing from schema: %s" % sorted(missing),
        )


if __name__ == "__main__":
    unittest.main()
